version: '3'
services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d testdb -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5