-- create "task_manegements" table
CREATE TABLE "task_manegements" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "task_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "task_manegements_tasks_task_manegement" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE NO ACTION,
    CONSTRAINT "task_manegements_users_task_manegements" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION
);
