-- create "tasks" table
CREATE TABLE "tasks" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "title" character varying NOT NULL,
    "deadline_timestamp" timestamptz NULL,
    "completed_at" timestamptz NULL,
    "message_id" bigint NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "tasks_messages_task" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE SET NULL
);
