name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github
          ls -al
          cd workflows
          ls -al